logger:
  path: log/development.log
  level: <%= Logger::DEBUG %>
rabbitmq:
  host: <%= ENV.fetch('RABBITMQ_HOST') %>
  username: <%= ENV.fetch('RABBITMQ_USER') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD') %>
